let buttonData = [
    { id: 'abom', classes: 'data-label lgd-btn tag-a threat-5' },
    { id: 'av', classes: 'data-label lgd-btn tag-a threat-4' },
    { id: 'asm', classes: 'data-label lgd-btn tag-a threat-5' },
    { id: 'a1', classes: 'data-label lgd-btn tag-a threat-4' },
    { id: 'angl', classes: 'data-label lgd-btn tag-a threat-3 ' },
    { id: 'angla', classes: 'data-label lgd-btn tag-a threat-5  ' },
    { id: 'ant', classes: 'data-label lgd-btn tag-a threat-3 ' },
    { id: 'apoc', classes: 'data-label lgd-btn tag-a threat-6' },
    { id: 'arcangl', classes: 'data-label lgd-btn tag-a threat-4' },
    { id: 'arnim', classes: 'data-label lgd-btn tag-a threat-3' },
    { id: 'avlch', classes: 'data-label lgd-btn tag-a threat-' },
    { id: 'zemo4', classes: 'data-label lgd-btn tag-b threat-4' },
    { id: 'mordo', classes: 'data-label lgd-btn tag-b threat-3' },
    { id: 'strck', classes: 'data-label lgd-btn tag-b threat-3' },
    { id: 'zemo3', classes: 'data-label lgd-btn tag-b threat-3' },
    { id: 'beast', classes: 'data-label lgd-btn tag-b threat-3 ' },
    { id: 'brb', classes: 'data-label lgd-btn tag-b threat-4 ' },
    { id: 'bshp', classes: 'data-label lgd-btn tag-b threat-4' },
    { id: 'bb5', classes: 'data-label lgd-btn tag-b threat-5' },
    { id: 'cat', classes: 'data-label lgd-btn tag-b threat-3 ' },
    { id: 'bdwarf', classes: 'data-label lgd-btn tag-b threat-4' },
    { id: 'bpant4', classes: 'data-label lgd-btn tag-b threat-4 ' },
    { id: 'bast', classes: 'data-label lgd-btn tag-b threat-3 ' },
    { id: 'bswan', classes: 'data-label lgd-btn tag-b threat-4' },
    { id: 'bwid2', classes: 'data-label lgd-btn tag-b threat-2  ' },
    { id: 'bwid3', classes: 'data-label lgd-btn tag-b threat-3  ' },
    { id: 'blade', classes: 'data-label lgd-btn tag-b threat-4 ' },
    { id: 'bmrvl', classes: 'data-label lgd-btn tag-b threat-' },
    { id: 'bob', classes: 'data-label lgd-btn tag-b threat-2' },
    { id: 'bullseye', classes: 'data-label lgd-btn tag-b threat-2' },
    { id: 'cbl', classes: 'data-label lgd-btn tag-c threat-5 ' },
    { id: 'sam', classes: 'data-label lgd-btn tag-c threat-3 ' },
    { id: 'cap2', classes: 'data-label lgd-btn tag-c threat-4 ' },
    { id: 'cap3', classes: 'data-label lgd-btn tag-c threat-4 ' },
    { id: 'capmrvl4', classes: 'data-label lgd-btn tag-c threat-4  ' },
    { id: 'capmrvl5', classes: 'data-label lgd-btn tag-c threat-5  ' },
    { id: 'crng', classes: 'data-label lgd-btn tag-c threat-4' },
    { id: 'cassnova', classes: 'data-label lgd-btn tag-c threat-5' },
    { id: 'clea', classes: 'data-label lgd-btn tag-c threat-3' },
    { id: 'colo', classes: 'data-label lgd-btn tag-c threat-4' },
    { id: 'corvus', classes: 'data-label lgd-btn tag-c threat-4' },
    { id: 'cgr', classes: 'data-label lgd-btn tag-c threat-6' },
    { id: 'crimd', classes: 'data-label lgd-btn tag-c threat-4' },
    { id: 'xbone1', classes: 'data-label lgd-btn tag-c threat-3' },
    { id: 'xbone2', classes: 'data-label lgd-btn tag-c threat-3' },
    { id: 'crystl', classes: 'data-label lgd-btn tag-c threat-3 ' },
    { id: 'cyc', classes: 'data-label lgd-btn tag-c threat-4' },
    { id: 'dd', classes: 'data-label lgd-btn tag-d threat-4' },
    { id: 'drkstr', classes: 'data-label lgd-btn tag-d threat-3' },
    { id: 'dpool', classes: 'data-label lgd-btn tag-d threat-3 ' },
    { id: 'ock4', classes: 'data-label lgd-btn tag-d threat-4' },
    { id: 'ock3', classes: 'data-label lgd-btn tag-d threat-3' },
    { id: 'strng', classes: 'data-label lgd-btn tag-d threat-5' },
    { id: 'strgsprm', classes: 'data-label lgd-btn tag-d threat-5' },
    { id: 'voodoo', classes: 'data-label lgd-btn tag-d threat-4 ' },
    { id: 'dmno', classes: 'data-label lgd-btn tag-d threat-3 ' },
    { id: 'dorm', classes: 'data-label lgd-btn tag-d threat-8' },
    { id: 'drac', classes: 'data-label lgd-btn tag-d threat-5' },
    { id: 'drax', classes: 'data-label lgd-btn tag-d threat-3' },
    { id: 'maw', classes: 'data-label lgd-btn tag-e threat-5' },
    { id: 'echo', classes: 'data-label lgd-btn tag-e threat-' },
    { id: 'elctro', classes: 'data-label lgd-btn tag-e threat-4' },
    { id: 'elktra', classes: 'data-label lgd-btn tag-e threat-4' },
    { id: 'elsa', classes: 'data-label lgd-btn tag-e threat-4' },
    { id: 'emma', classes: 'data-label lgd-btn tag-e threat-4' },
    { id: 'encht', classes: 'data-label lgd-btn tag-e threat-4' },
    { id: 'exods', classes: 'data-label lgd-btn tag-e threat-5' },
    { id: 'frank', classes: 'data-label lgd-btn tag-f threat-4' },
    { id: 'gmbt', classes: 'data-label lgd-btn tag-g threat-3' },
    { id: 'gmra', classes: 'data-label lgd-btn tag-g threat-4 ' },
    { id: 'gr', classes: 'data-label lgd-btn tag-g threat-5' },
    { id: 'gwen', classes: 'data-label lgd-btn tag-g threat-3' },
    { id: 'glad', classes: 'data-label lgd-btn tag-g threat-6' },
    { id: 'gorg', classes: 'data-label lgd-btn tag-g threat-3' },
    { id: 'gobbo', classes: 'data-label lgd-btn tag-g threat-4' },
    { id: 'groot', classes: 'data-label lgd-btn tag-g threat-3' },
    { id: 'gwenom', classes: 'data-label lgd-btn tag-g threat-4' },
    { id: 'gpool', classes: 'data-label lgd-btn tag-g threat-4  ' },
    { id: 'hwkeye', classes: 'data-label lgd-btn tag-h threat-3' },
    { id: 'hmdall', classes: 'data-label lgd-btn tag-h threat-3' },
    { id: 'helaquee', classes: 'data-label lgd-btn tag-h threat-4' },
    { id: 'honeybad', classes: 'data-label lgd-btn tag-h threat-2' },
    { id: 'hood', classes: 'data-label lgd-btn tag-h threat-3' },
    { id: 'hulk', classes: 'data-label lgd-btn tag-h threat-6' },
    { id: 'hulkbust', classes: 'data-label lgd-btn tag-h threat-6' },
    { id: 'iceman', classes: 'data-label lgd-btn tag-i threat-3' },
    { id: 'ironman4', classes: 'data-label lgd-btn tag-i threat-4' },
    { id: 'ironfist', classes: 'data-label lgd-btn tag-i threat-3' },
    { id: 'ironman3', classes: 'data-label lgd-btn tag-i threat-3' },
    { id: 'jeangrey', classes: 'data-label lgd-btn tag-j threat-5' },
    { id: 'juggs', classes: 'data-label lgd-btn tag-j threat-5' },
    { id: 'karnak', classes: 'data-label lgd-btn tag-k threat-3' },
    { id: 'killmong', classes: 'data-label lgd-btn tag-k threat-4' },
    { id: 'killsurper', classes: 'data-label lgd-btn tag-k threat-4' },
    { id: 'kingbb', classes: 'data-label lgd-btn tag-k threat-6' },
    { id: 'kingtchalla', classes: 'data-label lgd-btn tag-k threat-5' },
    { id: 'kingpin', classes: 'data-label lgd-btn tag-k threat-4' },
    { id: 'klaw', classes: 'data-label lgd-btn tag-k threat-5' },
    { id: 'kraven', classes: 'data-label lgd-btn tag-k threat-3' },
    { id: 'ladymstr', classes: 'data-label lgd-btn tag-k threat-' },
    { id: 'ladysif', classes: 'data-label lgd-btn tag-l threat-4' },
    { id: 'lizard', classes: 'data-label lgd-btn tag-l threat-3' },
    { id: 'lockjaw', classes: 'data-label lgd-btn tag-l threat-3' },
    { id: 'logan', classes: 'data-label lgd-btn tag-l threat-4' },
    { id: 'lokigod', classes: 'data-label lgd-btn tag-l threat-4' },
    { id: 'lokiprin', classes: 'data-label lgd-btn tag-l threat-5' },
    { id: 'lukecage', classes: 'data-label lgd-btn tag-l threat-3' },
    { id: 'modok', classes: 'data-label lgd-btn tag-m threat-5' },
    { id: 'modoksup', classes: 'data-label lgd-btn tag-m threat-4' },
    { id: 'magik', classes: 'data-label lgd-btn tag-m threat-3' },
    { id: 'magneto', classes: 'data-label lgd-btn tag-m threat-6' },
    { id: 'malekith', classes: 'data-label lgd-btn tag-m threat-7' },
    { id: 'manthing', classes: 'data-label lgd-btn tag-m threat-3' },
    { id: 'maverick', classes: 'data-label lgd-btn tag-m threat-3' },
    { id: 'maximus', classes: 'data-label lgd-btn tag-m threat-4' },
    { id: 'medusa', classes: 'data-label lgd-btn tag-m threat-4' },
    { id: 'mephisto', classes: 'data-label lgd-btn tag-m threat-5' },
    { id: 'mrsini', classes: 'data-label lgd-btn tag-m threat-4' },
    { id: 'moonknt', classes: 'data-label lgd-btn tag-m threat-3' },
    { id: 'msmarvel', classes: 'data-label lgd-btn tag-m threat-3' },
    { id: 'mysterio', classes: 'data-label lgd-btn tag-m threat-3' },
    { id: 'mystique', classes: 'data-label lgd-btn tag-m threat-3' },
    { id: 'mbaku', classes: 'data-label lgd-btn tag-k threat-4' },
    { id: 'namor', classes: 'data-label lgd-btn tag-n threat-5' },
    { id: 'nebula', classes: 'data-label lgd-btn tag-n threat-2' },
    { id: 'nickfuryjr', classes: 'data-label lgd-btn tag-n threat-4' },
    { id: 'nickfury', classes: 'data-label lgd-btn tag-n threat-3' },
    { id: 'nightcra', classes: 'data-label lgd-btn tag-n threat-4' },
    { id: 'nova', classes: 'data-label lgd-btn tag-n threat-5' },
    { id: 'nkantu', classes: 'data-label lgd-btn tag-n threat-3' },
    { id: 'okoye', classes: 'data-label lgd-btn tag-o threat-2' },
    { id: 'omegared', classes: 'data-label lgd-btn tag-o threat-4' },
    { id: 'phoenix', classes: 'data-label lgd-btn tag-p threat-6' },
    { id: 'profx', classes: 'data-label lgd-btn tag-p threat-4' },
    { id: 'prwlr', classes: 'data-label lgd-btn tag-k threat-' },
    { id: 'proximam', classes: 'data-label lgd-btn tag-p threat-3' },
    { id: 'psylocke', classes: 'data-label lgd-btn tag-p threat-4' },
    { id: 'punisher', classes: 'data-label lgd-btn tag-p threat-3' },
    { id: 'pyro', classes: 'data-label lgd-btn tag-p threat-3' },
    { id: 'quicksil', classes: 'data-label lgd-btn tag-q threat-3' },
    { id: 'redguard', classes: 'data-label lgd-btn tag-r threat-3' },
    { id: 'redskull1', classes: 'data-label lgd-btn tag-r threat-4' },
    { id: 'redskull2', classes: 'data-label lgd-btn tag-r threat-5' },
    { id: 'redskull3', classes: 'data-label lgd-btn tag-r threat-4' },
    { id: 'rhino', classes: 'data-label lgd-btn tag-r threat-4' },
    { id: 'rocket', classes: 'data-label lgd-btn tag-r threat-2' },
    { id: 'rogue', classes: 'data-label lgd-btn tag-r threat-4' },
    { id: 'ronan', classes: 'data-label lgd-btn tag-r threat-4' },
    { id: 'ronin', classes: 'data-label lgd-btn tag-k threat-' },
    { id: 'sabretoo', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'sabreapex', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'sandman', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'scarletsp', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'scarletw', classes: 'data-label lgd-btn tag-s threat-5' },
    { id: 'sentinel', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'sentprime', classes: 'data-label lgd-btn tag-s threat-5' },
    { id: 'shdowking', classes: 'data-label lgd-btn tag-s threat-5' },
    { id: 'shdowcat', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'sldd', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'shang', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'shehulk', classes: 'data-label lgd-btn tag-s threat-6' },
    { id: 'shocker', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'shuri', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'silk', classes: 'data-label lgd-btn tag-k threat-' },
    { id: 'slvrsabl', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'sin', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'skurge', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'ssm', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'spectrum', classes: 'data-label lgd-btn tag-k threat-' },
    { id: 'spham', classes: 'data-label lgd-btn tag-s threat-2' },
    { id: 'smcore', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'spmiles', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'sp2099', classes: 'data-label lgd-btn tag-s threat-5' },
    { id: 'spnoir', classes: 'data-label lgd-btn tag-k threat-' },
    { id: 'spwmn', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'sqrlgirl', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'starlord', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'steverog', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'storm', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'sunspot', classes: 'data-label lgd-btn tag-s threat-4' },
    { id: 'sprgiant', classes: 'data-label lgd-btn tag-s threat-3' },
    { id: 'taskmast', classes: 'data-label lgd-btn tag-t threat-3' },
    { id: 'thanos', classes: 'data-label lgd-btn tag-t threat-6' },
    { id: 'bwid4', classes: 'data-label lgd-btn tag-b threat-4' },
    { id: 'blob', classes: 'data-label lgd-btn tag-b threat-3' },
    { id: 'ihulk', classes: 'data-label lgd-btn tag-i threat-7' },
    { id: 'thorjane', classes: 'data-label lgd-btn tag-m threat-5' },
    { id: 'ogtorch', classes: 'data-label lgd-btn tag-o threat-3' },
    { id: 'wreckcrew', classes: 'data-label lgd-btn tag-w threat-4' },
    { id: 'thor2', classes: 'data-label lgd-btn tag-t threat-6' },
    { id: 'thor1', classes: 'data-label lgd-btn tag-t threat-5' },
    { id: 'tigra', classes: 'data-label lgd-btn tag-k threat-' },
    { id: 'toad', classes: 'data-label lgd-btn tag-t threat-2' },
    { id: 'ulik', classes: 'data-label lgd-btn tag-u threat-5' },
    { id: 'ultmiles', classes: 'data-label lgd-btn tag-s threat-' },
    { id: 'ultron', classes: 'data-label lgd-btn tag-u threat-4' },
    { id: 'ultyrant', classes: 'data-label lgd-btn tag-u threat-5' },
    { id: 'ursamajo', classes: 'data-label lgd-btn tag-u threat-4' },
    { id: 'valkyrie', classes: 'data-label lgd-btn tag-v threat-3' },
    { id: 'venom', classes: 'data-label lgd-btn tag-v threat-4' },
    { id: 'viper', classes: 'data-label lgd-btn tag-v threat-3' },
    { id: 'vision', classes: 'data-label lgd-btn tag-v threat-4' },
    { id: 'vulture', classes: 'data-label lgd-btn tag-v threat-3' },
    { id: 'warmachi', classes: 'data-label lgd-btn tag-w threat-3' },
    { id: 'warlock', classes: 'data-label lgd-btn tag-w threat-3' },
    { id: 'wasp', classes: 'data-label lgd-btn tag-w threat-3' },
    { id: 'weaponx', classes: 'data-label lgd-btn tag-w threat-3' },
    { id: 'werewolf', classes: 'data-label lgd-btn tag-w threat-5' },
    { id: 'bucky1', classes: 'data-label lgd-btn tag-w threat-3' },
    { id: 'bucky2', classes: 'data-label lgd-btn tag-w threat-4' },
    { id: 'wolvie', classes: 'data-label lgd-btn tag-w threat-4' },
    { id: 'wong', classes: 'data-label lgd-btn tag-w threat-2' },
    { id: 'x23', classes: 'data-label lgd-btn tag-x threat-3' },
    { id: 'yondu', classes: 'data-label lgd-btn tag-y threat-4' },
];

