let filters = [
    { id: 'tag-a', label: 'A', class: 'filter' },
    { id: 'tag-b', label: 'B', class: 'filter' },
    { id: 'tag-c', label: 'C', class: 'filter' },
    { id: 'tag-d', label: 'D', class: 'filter' },
    { id: 'tag-e', label: 'E', class: 'filter' },
    { id: 'tag-f', label: 'F', class: 'filter' },
    { id: 'tag-g', label: 'G', class: 'filter' },
    { id: 'tag-h', label: 'H', class: 'filter' },
    { id: 'tag-i', label: 'I', class: 'filter' },
    { id: 'tag-j', label: 'J', class: 'filter' },
    { id: 'tag-k', label: 'K', class: 'filter' },
    { id: 'tag-l', label: 'L', class: 'filter' },
    { id: 'tag-m', label: 'M', class: 'filter' },
    { id: 'tag-n', label: 'N', class: 'filter' },
    { id: 'tag-o', label: 'O', class: 'filter' },
    { id: 'tag-p', label: 'P', class: 'filter' },
    { id: 'tag-q', label: 'Q', class: 'filter' },
    { id: 'tag-r', label: 'R', class: 'filter' },
    { id: 'tag-s', label: 'S', class: 'filter' },
    { id: 'tag-t', label: 'T', class: 'filter' },
    { id: 'tag-u', label: 'U', class: 'filter' },
    { id: 'tag-v', label: 'V', class: 'filter' },
    { id: 'tag-w', label: 'W', class: 'filter' },
    { id: 'tag-x', label: 'X', class: 'filter' },
    { id: 'tag-y', label: 'Y', class: 'filter' },

    // { id: 'afrce', label: 'A-Force', class: 'filter affil' },
    // { id: 'asgrd', label: 'Asgard', class: 'filter affil' },
    // { id: 'avngrs', label: 'Avengers', class: 'filter affil' },
    // { id: 'blkordr', label: 'Black Order', class: 'filter affil' },
    // { id: 'brothrhd', label: 'Brotherhood', class: 'filter affil' },
    // { id: 'cabal', label: 'Cabal', class: 'filter affil' },
    // { id: 'convcl', label: 'Convocation', class: 'filter affil' },
    // { id: 'crmlsndct', label: 'Criminal Synd', class: 'filter affil' },
    // { id: 'darkdim', label: 'Dark Dimension', class: 'filter affil' },
    // { id: 'defndr', label: 'Defenders', class: 'filter affil' },
    // { id: 'gotg', label: 'GotG', class: 'filter affil' },
    // { id: 'hellf', label: 'Hellfire Club', class: 'filter affil' },
    // { id: 'hydra', label: 'HYDRA', class: 'filter affil' },
    // { id: 'inhum', label: 'Inhumans', class: 'filter affil' },
    // { id: 'meph', label: 'Legion of Lost', class: 'filter affil' },
    // { id: 'midson', label: 'Midnight Sons', class: 'filter affil' },
    // { id: 'newmu', label: 'New Mutants', class: 'filter affil' },
    // { id: 'sheild', label: 'S.H.I.E.L.D.', class: 'filter affil' },
    // { id: 'sentinl', label: 'Sentinels', class: 'filter affil' },
    // { id: 'apoc', label: 'Servants of Apoc', class: 'filter affil' },
    // { id: 'spdrfoe', label: 'Spider-Foes', class: 'filter affil' },
    // { id: 'thralls', label: 'Thralls of Drac', class: 'filter affil' },
    // { id: 'xmen', label: 'X-Men', class: 'filter affil' },
    // { id: 'wakan', label: 'Wakanda', class: 'filter affil' },
    // { id: 'weapx', label: 'Weapon X', class: 'filter affil' },
    // { id: 'webwar', label: 'Web Warriors', class: 'filter affil' },
    // { id: 'winter', label: 'Winter Guard', class: 'filter affil' },
    // { id: 'xforce', label: 'X-Force', class: 'filter affil' },


    { id: 'threat-2', label: 'Threat 2', class: 'filter' },
    { id: 'threat-3', label: 'Threat 3', class: 'filter' },
    { id: 'threat-4', label: 'Threat 4', class: 'filter' },
    { id: 'threat-5', label: 'Threat 5', class: 'filter' },
    { id: 'threat-6', label: 'Threat 6', class: 'filter' },
    { id: 'threat-4', label: 'Threat 7', class: 'filter' },
    { id: 'threat-8', label: 'Threat 8', class: 'filter' },
    { id: 'show-all', label: 'Show All', class: 'filter' }
];